#!/bin/bash

metricsFile=$1
nodePath=$2

rm -rf ${metricsFile}
touch ${metricsFile}

CPU_LOAD="$(uptime | awk '{for(i=NF;i>=1;i--) printf "%s ", $i;print ""}' | cut -f 3 -d ' ' | rev | cut -c 2- | rev | sed 's/,/./g')"
FREE_DISK="$(df --total | grep total | sed 's/  */ /g' | cut -f 4 -d ' ')"
TOTAL_DISK="$(df --total | grep total | sed 's/  */ /g' | cut -f 2 -d ' ')"
FREE_RAM="$(free | sed -n 2p | sed 's/  */ /g' | cut -f 4 -d ' ')"
TOTAL_RAM="$(free | sed -n 2p | sed 's/  */ /g' | cut -f 2 -d ' ')"
FREE_SWAP="$(free | sed -n 3p | sed 's/  */ /g' | cut -f 4 -d ' ')"
TOTAL_SWAP="$(free | sed -n 3p | sed 's/  */ /g' | cut -f 2 -d ' ')"
NUM_PROCESSES="$(ps aux --no-heading | wc -l)"
NUM_CORES="$(nproc)"
KERNEL_VER="$(uname -r)"
LOGGED_USERS="$(users | wc -w)"
DNS_NAME="$(dnsdomainname)"

echo ${nodePath} > ${metricsFile}
echo "cpu_load : double = ${CPU_LOAD}" >> ${metricsFile}
echo "free_disk : integer = ${FREE_DISK}" >> ${metricsFile}
echo "total_disk : integer = ${TOTAL_DISK}" >> ${metricsFile}
echo "free_ram : integer = ${FREE_RAM}" >> ${metricsFile}
echo "total_ram : integer = ${TOTAL_RAM}" >> ${metricsFile}
echo "free_swap : integer = ${FREE_SWAP}" >> ${metricsFile}
echo "total_swap : integer = ${TOTAL_SWAP}" >> ${metricsFile}
echo "num_processes : integer = ${NUM_PROCESSES}" >> ${metricsFile}
echo "num_cores : integer = ${NUM_CORES}" >> ${metricsFile}
echo -e "kernel_ver : string = \"${KERNEL_VER}\"" >> ${metricsFile}
echo "logged_users : integer = ${LOGGED_USERS}" >> ${metricsFile}
echo "dns_name : set string = {${DNS_NAME}}" >> ${metricsFile}
