#!/bin/bash

metricsFile=$2

rm -rf $2

cp $1 $2

CPU_LOAD="$(uptime | awk '{for(i=NF;i>=1;i--) printf "%s ", $i;print ""}' | cut -f 3 -d ' ' | rev | cut -c 2- | rev | sed 's/,/./g')"
FREE_DISK="$(df --total | grep total | sed 's/  */ /g' | cut -f 4 -d ' ')"
TOTAL_DISK="$(df --total | grep total | sed 's/  */ /g' | cut -f 2 -d ' ')"
FREE_RAM="$(free | sed -n 2p | sed 's/  */ /g' | cut -f 4 -d ' ')"
TOTAL_RAM="$(free | sed -n 2p | sed 's/  */ /g' | cut -f 2 -d ' ')"
FREE_SWAP="$(free | sed -n 3p | sed 's/  */ /g' | cut -f 4 -d ' ')"
TOTAL_SWAP="$(free | sed -n 3p | sed 's/  */ /g' | cut -f 2 -d ' ')"
NUM_PROCESSES="$(ps aux --no-heading | wc -l)"
NUM_CORES="$(nproc)"
KERNEL_VER="$(uname -r)"
LOGGED_USERS="$(users | wc -w)"
DNS_NAME="$(dnsdomainname)"


echo "cpu_load : double = ${CPU_LOAD}" >> $2
echo "free_disk : int = ${FREE_DISK}" >> $2
echo "total_disk : int = ${TOTAL_DISK}" >> $2
echo "free_ram : int = ${FREE_RAM}" >> $2
echo "total_ram : int = ${TOTAL_RAM}" >> $2
echo "free_swap : int = ${FREE_SWAP}" >> $2
echo "total_swap : int = ${TOTAL_SWAP}" >> $2
echo "num_processes : int = ${NUM_PROCESSES}" >> $2
echo "num_cores : int = ${NUM_CORES}" >> $2
echo -e "kernel_ver : string = \"${KERNEL_VER}\"" >> $2
echo "logged_users : int = ${LOGGED_USERS}" >> $2
echo "dns_name : set string = {${DNS_NAME}}" >> $2
