#!/bin/sh

java -cp $PWD/bin:lib/cup.jar:lib/JLex.jar -Djava.rmi.server.codebase=file:$PWD/bin -Djava.rmi.server.hostname=localhost -Djava.security.policy=utility/general.policy pl.edu.mimuw.cloudatlas.fetcher.Fetcher localhost utility/fetcher.ini utility/start_file utility/metrics_file
